name: chess_lib
description: Dart library for chess. Use this package for modelling a game of chess.

version: 0.1.0+1

repository: https://github.com/bedardjo/chess_lib.git

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
